### ISSUE TITLE
vSphere CPI failing because guest hostname is not reported

### ISSUE THREAD

**Issue by shkarface** [siderolabs/talos-vmtoolsd#11]
I've been trying to get vSphere CPI working, but I get the following error:

```logs
I0316 02:11:50.580809       1 node_controller.go:427] Initializing node dev-controlplane-1 with cloud provider
I0316 02:11:50.581000       1 search.go:76] WhichVCandDCByNodeID nodeID: dev-controlplane-1
I0316 02:11:50.591716       1 search.go:208] Found node dev-controlplane-1 as vm=VirtualMachine:vm-158 in vc=vcenter.home.arpa and datacenter=hetzner-cloud
I0316 02:11:50.591864       1 search.go:210] Hostname: , UUID: 421fa7c6-e142-4587-d2af-7e480929eb9f
I0316 02:11:50.591956       1 nodemanager.go:138] Discovered VM using FQDN or short-hand name
E0316 02:11:50.596703       1 node_controller.go:236] error syncing 'dev-controlplane-1': failed to get provider ID for node dev-controlplane-1 at cloudprovider: failed to get instance ID from cloud provider: VM Guest hostname is empty, requeuing
```

The guest hostname check from CPI is done here:
https://github.dev/kubernetes/cloud-provider-vsphere/blob/1125332f9b461f399bdf7910fb957975bdc1090c/pkg/cloudprovider/vsphere/nodemanager.go#L226-L228

**Comment by gnur** [comment]
We are trying to achieve the same result (running the vsphere CPI), did you get it working?

**Comment by robinelfrink** [comment]
Sounds like either the guest agent is not running yet, or no hostname is set inside the OS. Can you check both?

**Comment by shkarface** [comment]
> We are trying to achieve the same result (running the vsphere CPI), did you get it working? 

I just ended up not installing the CPI at all, the CSI worked out of the box without the CPI given that the hostname and the VM Name in vCenter are identical

**Comment by shkarface** [comment]
> Sounds like either the guest agent is not running yet, or no hostname is set inside the OS. Can you check both?

At the time of writing, I made sure that both were actually set. It seems like after some time it fails to report the information (even now after using it as a system extension)

**Comment by gnur** [comment]
@shkarface Do you have guide on doing this? We couldn't get this working without the CPI.

**Comment by shkarface** [comment]
> @shkarface Do you have guide on doing this? We couldn't get this working without the CPI.

I can share the manifests used to deploy the CSI.

It's the upstream CSI deployment manifests, I just deleted the windows only DaemonSet.
I think the key here was making sure the kubernetes node name was exactly as the VM Name in vCenter.

**Comment by onlineque** [comment]
Guys I know this is an already closed one, but this you manage to fix this issue ?
I am facing exactly the same situation, where talos-vmtoolsd is not reporting DNS hostname up to vcenter and CPI is failing due to that.
I've found reboot helps to start reporting, but as I try to deploy the whole cluster with Terraform, this is not a way to go for me.
Any ideas ? 
Thanks !
