### ISSUE TITLE
Enable default repo settings similar to other siderolabs repos

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos-vmtoolsd#14]
Coming in from this: https://github.com/siderolabs/talos-vmtoolsd/pull/12#issuecomment-2021991973

i would be beneficial to have this repo have default settings similar to other repos under the organization.

Have a default main branch and have the standard repo branch protection settings enabled. 

@robinelfrink / @lennardk I can help get this started

**Comment by robinelfrink** [comment]
Yes, I'm all in for uniform repository settings :)

I'll make sure we rework the repo-content with kres as soon as we have released 0.5.0.

**Comment by frezbo** [comment]
> Yes, I'm all in for uniform repository settings :)
> 
> I'll make sure we rework the repo-content with kres as soon as we have released 0.5.0.

Yup great :+1:

**Comment by frezbo** [comment]
I'll put up a draft PR to help things to be easier, and once 0.5.0 is released, will enforce the repository settings.

**Comment by frezbo** [comment]
Oh, i didn't realize 0.5.0 is already cut that was fast, I'll start by renaming the branch to main, WDYT?

**Comment by robinelfrink** [comment]
I _just_ _now_ created the release :) Yes, if you will, please go.

**Comment by frezbo** [comment]
> I _just_ _now_ created the release :) Yes, if you will, please go.

Done, might need this local updates:

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by robinelfrink** [comment]
Thanks. I've updated the workflow definition to reflect the branch rename, even though I suspect kres will make that obsolete anyway.

**Comment by frezbo** [comment]
Yeh, kres generates even gh workflow files
