### ISSUE TITLE
Unable to restart guest OS using vSphere

### ISSUE THREAD

**Issue by rgomezceis** [siderolabs/talos-vmtoolsd#21]
Using latest release..

First reboot works well, but when vm starts and I want to restart it again it fails with:

**"Cannot complete operation because VMware Tools is not running in this virtual machine. Failed to reset the virtual machine: Cannot execute scripts."**

Pod is running without any error log.

```
kube-system          talos-vmtoolsd-wmjjk                           1/1     Running
```

**Comment by rgomezceis** [comment]
Just this:

$ kubectl logs -n kube-system talos-vmtoolsd-rh4c7
{"level":"info","msg":"talos-vmtoolsd version latest\nCopyright 2020-2022 Oliver Kuckertz <oliver.kuckertz@mologie.de>\nThis program is free software and available under the Apache 2.0 license."}

**Comment by jonkerj** [comment]
Hmm that's not much. Could you add these env vars to your container spec, and inspect your logs again? According to `main.go`, this is how one sets the log level.

```
env:
- name: LOG_LEVEL
  value: debug  # or even trace
```

**Comment by rgomezceis** [comment]
```
{"level":"info","msg":"talos-vmtoolsd version latest\nCopyright 2020-2022 Oliver Kuckertz <oliver.kuckertz@mologie.de>\nThis program is free software and available under the Apache 2.0 license."}
{"level":"debug","module":"vmware-guestinfo","msg":"Opened channel 0"}
{"level":"debug","module":"vmware-guestinfo","msg":"Opened channel 1"}
{"handler_name":"reset","level":"debug","module":"nanotoolbox","msg":"incoming RPC request"}
{"level":"debug","module":"tboxcmds","msg":"sending hostname: ceis-worker-3"}
{"level":"debug","module":"tboxcmds","msg":"sending OS full name: Talos v1.7.4-cb3a8308"}
{"level":"debug","module":"tboxcmds","msg":"sending OS short name: Talos v1.7.4"}
{"level":"debug","module":"tboxcmds","msg":"GuestNicInfo: adding name=eth0 mac={mac} ip={ipv4}"}
{"level":"debug","module":"tboxcmds","msg":"GuestNicInfo: adding name=eth0 mac={mac }ip={ipv6}"}
{"handler_name":"Capabilities_Register","level":"debug","module":"nanotoolbox","msg":"incoming RPC request"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"handler_name":"Vix_1_Relayed_Command","level":"debug","module":"nanotoolbox","msg":"incoming RPC request"}
{"command":"vix","level":"debug","module":"nanotoolbox","msg":"sending tools state version=\"Talos v1.7.4-cb3a8308\" versionShort=\"Talos v1.7.4\" hostname=\"ceis-worker-3\""}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}
{"level":"debug","module":"vmware-guestinfo","msg":"No message to retrieve"}

```

**Comment by robinelfrink** [comment]
I'm seeing the same with `talos-vmtoolsd` as a system extension on vCloud. What's interersting, is that after the reboot `talos-vmtoolsd` properly reports IP addresses.

I'll try to find out what's going on here.

**Comment by robinelfrink** [comment]
This is a tricky one. Reboot works only after poweron; subsequent requests throw a java exception on the esx host, with this error in the UI:

```json
      "message": "Cannot complete operation because VMware Tools is not running in this virtual machine.\nFailed to reset the virtual machine: Cannot execute scripts.",
      "faultMessage": [
        {
          "_type": "com.vmware.vim.binding.impl.vmodl.LocalizableMessageImpl",
          "key": "msg.vigor.reset.fail",
          "arg": [
            {
              "_type": "com.vmware.vim.binding.impl.vmodl.KeyAnyValueImpl",
              "key": "1",
              "value": "msg.foundryErrMsgId.VIX_E_POWEROP_SCRIPTS_NOT_AVAILABLE"
            }
          ],
          "message": "Failed to reset the virtual machine: Cannot execute scripts."
        }
      ]
```

I'll continue to try to figure out what's going on, but don't expect a fix very soon. If you're automating the reboots i suggest you try a shutdown followed by a powerup for now.

**Comment by rgomezceis** [comment]
> Reboot works only after poweron; subsequent requests throw a java exception on the esx host, with this error in the UI:
> 
> ```json
>       "message": "Cannot complete operation because VMware Tools is not running in this virtual machine.\nFailed to reset the virtual machine: Cannot execute scripts.",
>       "faultMessage": [
>         {
>           "_type": "com.vmware.vim.binding.impl.vmodl.LocalizableMessageImpl",
>           "key": "msg.vigor.reset.fail",
>           "arg": [
>             {
>               "_type": "com.vmware.vim.binding.impl.vmodl.KeyAnyValueImpl",
>               "key": "1",
>               "value": "msg.foundryErrMsgId.VIX_E_POWEROP_SCRIPTS_NOT_AVAILABLE"
>             }
>           ],
>           "message": "Failed to reset the virtual machine: Cannot execute scripts."
>         }
>       ]
> ```
> 
> I'll continue to try to figure out what's going on, but don't expect a fix very soon. If you're automating the reboots i suggest you try a shutdown followed by a powerup for now.
> 
> Here's the full response in the vSphere UI: [stacktrace.json](https://github.com/user-attachments/files/16009216/stacktrace.json)

So this bug is critical now because we need to use vSphere CPI to use vSphere CSI driver. 
vSphere CPI tries to find VM by DNS or IP but it can't.

```
E0718 09:32:40.401110       1 search.go:181] Error while looking for vm=ceis-worker-3(byIP) in vc={vcenter-ip} and datacenter=Datacenter: No VM found
I0718 09:32:40.401120       1 search.go:186] Did not find node ceis-worker-3 in vc={vcenter-ip} and datacenter=Datacenter
E0718 09:32:40.401138       1 nodemanager.go:161] WhichVCandDCByNodeID failed using VM name. Err: No VM found
E0718 09:32:40.401149       1 nodemanager.go:206] shakeOutNodeIDLookup failed. Err=No VM found
E0718 09:32:40.401164       1 node_controller.go:281] Error getting instance metadata for node addresses: error fetching node by provider ID: node not found, and error by node name: node not found
```

vmtools pod is running 
```
kube-system          talos-vmtoolsd-8s7rd                           1/1     Running            1 (10m ago)     30d     10.244.9.128    ceis-worker-3          <none>           <none>
```

![image](https://github.com/user-attachments/assets/0bf62739-a043-45f1-8d22-7f92a22179fc)
