### ISSUE TITLE
0.6.0 reporting incorrect OS uptime to monitoring solutions

### ISSUE THREAD

**Issue by mihkel** [siderolabs/talos-vmtoolsd#23]
I've a feeling that PR #22  has caused an issue with guest os uptime being reported so that monitoring systems like Zabbix 'think' that the Talos vm is constantly being rebooted.

Prior versions of vmtoolsd (pre 0.6.0) reported the item being empty. Since vers 0.6.0 the item has a value but we're seeing the item value being constantly reported as '00:00:03' creating an illusion that the vm is in some kind of a rebootalooza.

**Comment by robinelfrink** [comment]
It looks like the guestinfo is never updated apart from nic info. Can you try `image: wobin/talos-vmtoolsd:v0.6.0-2-g2f0bc74-dirty` to see if the changes in #24 work for you?

**Comment by mihkel** [comment]
@robinelfrink looks like it's fine now.

**Comment by robinelfrink** [comment]
> @robinelfrink looks like it's fine now.

Thanks for the feedback. Pull request awaiting approval.
