### ISSUE TITLE
Develop integration into Talos K8s token provisioning once available

### ISSUE THREAD

**Issue by mologie** [siderolabs/talos-vmtoolsd#3]
* The 0.15 milestone (now 1.0, delayed though) of Talos includes a change to auto-provision Talos API credentials in K8s (talos-systems/talos#4422). Talos-vmtoolsd can make use of this feature to simplify installation since no more config bootstrapping is needed.
* We can change the setup instructions to extend Talos' "extraManifests" config key if the auto-provisioning part works.
* Talos 1.0+ includes a system extensions feature that offers complete access to machined and thus the relevant part of Talos' API.

**Comment by dimatha** [comment]
Hi @mologie! Just for the note. I've just seen that additional functionality was added to Talos 1.0 => https://www.talos.dev/v1.0/learn-more/extension-services/ Not sure if that will help implementing Vmware tools in a better way. In addition, to the dependant issue: "smira removed this from the v0.15 milestone on 21 Feb".

**Comment by mologie** [comment]
Hi @dimatha, I am aware and in contact with the Sidero folks via Slack. So far I determined that talos-vmtoolsd can be implemented as Talos extension and thereby reduce configuration effort for the user, but I have not made any code or preview public yet. I will update this issue to reflect this. Appreciate your input regardless, thanks :)!

**Comment by dimatha** [comment]
Hey @mologie ! I just wanted to get back to this topic and check if you will continue your excellent work on the Vmware tools integration ?

**Comment by mologie** [comment]
Yes, in fact there is an open pull request at #8 by @bnason, and a working system extension in his fork of this tool. The only thing that blocks merging so far is extensive testing at my company, which is well underway. (Sorry for the lack of status updates, Brandon!)

If you'd like to please give his extension a shot with your cluster too. You can find a discussion about how to use it at:

https://taloscommunity.slack.com/archives/CPW6V498D/p1680742717739549

**Comment by mologie** [comment]
Hi @bobbled, the Talos Slack is unfortunately still a free instance limited to a 10K message history and I frankly don't remember. As far as I recall, "make image-vmware" with a custom extension path was sufficient.

Note however bnason's build likely has compatibility issues with Talos 1.5 due to #9, so I'd advise to wait until next week when his changes are integrated here.

I won't manage to develop a ready-made system extension image by next week, but have enough included to start playing with it in this issue (or a new one, this is about token stuff, not system images).

**Comment by bobbled** [comment]
@mologie , that's great to hear!

I did manage to figure out how to incorporate his extension into talos v1.6.1 using the [talos imager tool](https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#imager) and load it up on a v7.x vcenter, but as you mention above, I think there are either compatability issues with the newer version of talos, or the version of vmtools is just too old.

It reports "Running, version:2147483647 (Guest Managed)" when I look at the vm's summary.  The [only reference](https://kb.vmware.com/s/article/51988) I can find to that version is now about 5 years old, so I'm not sure even if it did work properly with the new version of Talos, that it would work with current versions of vsphere.

At any rate, thanks again.

**Comment by jonkerj** [comment]
This repo has changed hands since last comment (see #9). Our vision/focus would be to have talos-vmtoolsd run as a system extension, in the first place. We are going to fix up the tool for 1.6 compatibility, and dust of Brandon's work with the extension.

Given that all that succeeds and everything works, would there still be an interest to deploy talos-vmtoolsd in Kubernetes (not as an extension) and if so, what would be your use case?

**Comment by frezbo** [comment]
> Our vision/focus would be to have talos-vmtoolsd run as a system extension

With 1.6, the extension should also start as early as in maintenance mode reporting data back

**Comment by shkarface** [comment]
Having this as a system extension would be great, do you have any timelines in mind as when we can use this?

**Comment by robinelfrink** [comment]
Expect a system extention release in the next couple of days.
