### ISSUE TITLE
Include both tag and sha256 in deployment

### ISSUE THREAD

**Issue by Striar-Yunis** [siderolabs/talos-vmtoolsd#7]
The deployment given for v0.3.1 has the following:

```
image digest via https://github.com/mologie/talos-vmtoolsd/pkgs/container/talos-vmtoolsd/43215519?tag=0.3.1
image: ghcr.io/mologie/talos-vmtoolsd@sha256:cece8a312148ae50706b128a31b319addbabf1c6bc122ff9346904041a1c269d
```

Rather than just relying on the sha which can make it hard to automate version management of containers to air-gapped systems both can be combined.

````
image: ghcr.io/mologie/talos-vmtoolsd:0.3.1@sha256:cece8a312148ae50706b128a31b319addbabf1c6bc122ff9346904041a1c269d
```` 

PS: Thanks for all your work on this!

**Comment by mologie** [comment]
Ack, I see no downside in doing this, will add the tag too in future releases. Thanks!
